# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.crawler.Crawler:
        class: AppBundle\Crawler\Crawler
        arguments: []

    app.form.type.CrawlSearchType:
        class: AppBundle\Form\Type\CrawlSearchType
        tags:
            - { name: form.type}
